// Code generated by mockery v2.14.0. DO NOT EDIT.

package getcell_test

import (
	entity "github.com/julianVelandia/golang-sheets/internal/cell/core/entity"

	mock "github.com/stretchr/testify/mock"

	model "github.com/julianVelandia/golang-sheets/internal/platform/sheets/model"
)

// MapperMock is an autogenerated mock type for the Mapper type
type MapperMock struct {
	mock.Mock
}

// ModelToEntities provides a mock function with given fields: information
func (_m *MapperMock) ModelToEntities(information []model.Cell) []entity.Cell {
	ret := _m.Called(information)

	var r0 []entity.Cell
	if rf, ok := ret.Get(0).(func([]model.Cell) []entity.Cell); ok {
		r0 = rf(information)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Cell)
		}
	}

	return r0
}

type mockConstructorTestingTNewMapperMock interface {
	mock.TestingT
	Cleanup(func())
}

// NewMapperMock creates a new instance of MapperMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMapperMock(t mockConstructorTestingTNewMapperMock) *MapperMock {
	mock := &MapperMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
